export const FETCH_ENTITIES = "FETCH_ENTITIES";
export const FETCH_ATTRIBUTES = "FETCH_ATTRIBUTES";
export const FETCH_ENTITY_DATA = "FETCH_ENTITY_DATA";
export const DELETE_ENTITY_DATA = "DELETE_ENTITY_DATA";
